# Generated by Django 5.1.6 on 2025-04-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('crime_type', models.CharField(max_length=100)),
                ('modus_operandi', models.TextField()),
                ('weapon_used', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('case_status', models.CharField(max_length=50)),
            ],
        ),
    ]
