# Generated by Django 5.1.6 on 2025-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
