# Generated by Django 5.1.6 on 2025-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimes', '0002_crimerecord_latitude_crimerecord_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('modus_operandi', models.CharField(max_length=100)),
                ('weapon_used', models.CharField(max_length=100)),
                ('predicted_crime_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
