# Generated by Django 5.1.6 on 2025-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimes', '0003_crimeprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='punishment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
