# Generated by Django 5.1.6 on 2025-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimes', '0004_crimerecord_punishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='Indian_Penal_Code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
