# Generated by Django 5.1.6 on 2025-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimes', '0005_crimerecord_indian_penal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimerecord',
            name='Indian_Penal_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
